// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://byvkllvtaasnvtfbiolo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ5dmtsbHZ0YWFzbnZ0ZmJpb2xvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEzNTM3MTcsImV4cCI6MjA1NjkyOTcxN30.nAgCGySTSEmyeP-HwiKG71NNIwTNuLFULxSlGDSuaCE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);